[package]
name = "busses"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
futures = "0.3.31"
reqwest = { version = "0.12.12", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] } 
tokio = { version = "1.44.0", features = ["full"] }
